; *******************************************
; * Gemma-4-31B-it-qat                      *
; *******************************************

; [Gemma-4-31B-it-qat-128K-Q4-MTP4]
; model = /models/unsloth/gemma-4-31B-it-qat-GGUF/gemma-4-31B-it-qat-UD-Q4_K_XL.gguf
; model-draft = /models/unsloth/gemma-4-31B-it-qat-GGUF/mtp-gemma-4-31B-it.gguf
; ctx-size = 131072
; cache-type-k = q4_0
; cache-type-v = q4_0
; cache-type-k-draft = q4_0
; cache-type-v-draft = q4_0
; spec-type = draft-mtp
; spec-draft-n-max = 4
; temp = 0.6
; top-k = 64

; [Gemma-4-31B-it-qat-108K-Q4-MTP2-Vision]
; model = /models/unsloth/gemma-4-31B-it-qat-GGUF/gemma-4-31B-it-qat-UD-Q4_K_XL.gguf
; model-draft = /models/unsloth/gemma-4-31B-it-qat-GGUF/mtp-gemma-4-31B-it.gguf
; mmproj = /models/unsloth/gemma-4-31B-it-qat-GGUF/mmproj-BF16.gguf
; ctx-size = 110592
; cache-type-k = q4_0
; cache-type-v = q4_0
; cache-type-k-draft = q4_0
; cache-type-v-draft = q4_0
; spec-type = draft-mtp
; spec-draft-n-max = 2
; temp = 0.6
; top-k = 64
; image-min-tokens = -1

; [Gemma-4-31B-it-qat-116K-Q4-Vision]
; model = /models/unsloth/gemma-4-31B-it-qat-GGUF/gemma-4-31B-it-qat-UD-Q4_K_XL.gguf
; mmproj = /models/unsloth/gemma-4-31B-it-qat-GGUF/mmproj-BF16.gguf
; ctx-size = 118784
; cache-type-k = q4_0
; cache-type-v = q4_0
; temp = 0.6
; top-k = 64
; image-min-tokens = -1

