; *******************************************
; * Qwen3.6-35B-A3B-MTP                     *
; *******************************************

[Qwen36-35B-A3B-256K-Q4-MTP2-Vision]
model = /models/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/Qwen3.6-35B-A3B-UD-IQ4_NL.gguf
mmproj = /models/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/mmproj-BF16.gguf
ctx-size = 262144
cache-type-k = q4_0
cache-type-v = q4_0
cache-type-k-draft = q4_0
cache-type-v-draft = q4_0
spec-type = draft-mtp
spec-draft-n-max = 2
temp = 0.6
top-k = 20

[Qwen36-35B-A3B-256K-Q8-MTP2-Vision]
model = /models/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/Qwen3.6-35B-A3B-UD-IQ4_NL.gguf
mmproj = /models/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/mmproj-BF16.gguf
ctx-size = 262144
cache-type-k = q8_0
cache-type-v = q8_0
cache-type-k-draft = q8_0
cache-type-v-draft = q8_0
spec-type = draft-mtp
spec-draft-n-max = 2
temp = 0.6
top-k = 20

[Qwen36-35B-A3B-256K-Q8-MTP]
model = /models/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/Qwen3.6-35B-A3B-UD-IQ4_NL.gguf
ctx-size = 262144
cache-type-k = q8_0
cache-type-v = q8_0
cache-type-k-draft = q8_0
cache-type-v-draft = q8_0
spec-type = draft-mtp
spec-draft-n-max = 2
temp = 0.6
top-k = 20

[Qwen36-35B-A3B-256K-Q8-Vision]
model = /models/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/Qwen3.6-35B-A3B-UD-IQ4_NL.gguf
mmproj = /models/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/mmproj-BF16.gguf
ctx-size = 262144
cache-type-k = q8_0
cache-type-v = q8_0
temp = 0.6
top-k = 20

[Qwen36-35B-A3B-160K-Q4-MTP2]
model = /models/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/Qwen3.6-35B-A3B-UD-IQ4_NL.gguf
ctx-size = 163840
cache-type-k = q4_0
cache-type-v = q4_0
cache-type-k-draft = q4_0
cache-type-v-draft = q4_0
spec-type = draft-mtp
spec-draft-n-max = 2
temp = 0.6
top-k = 20

[Qwen36-35B-A3B-122K-Q8-MTP3]
model = /models/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/Qwen3.6-35B-A3B-UD-IQ4_NL.gguf
ctx-size = 131072
cache-type-k = q8_0
cache-type-v = q8_0
cache-type-k-draft = q8_0
cache-type-v-draft = q8_0
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 0.6
top-k = 20

