; *******************************************
; * Ornith-1.0-9B MTP                       *
; *******************************************

[Ornith-1.0-9B-256K-Q4KM-Q4-MTP]
model = /models/protoLabsAI/Ornith-1.0-9B-MTP-GGUF/ornith-9b-mtp-kl-Q4_K_M.gguf
ctx-size = 262144
cache-type-k-draft = q4_0
cache-type-v-draft = q4_0
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 0.6
top-k = 20

[Ornith-1.0-9B-256K-Q4KM-Q8-MTP]
model = /models/protoLabsAI/Ornith-1.0-9B-MTP-GGUF/ornith-9b-mtp-kl-Q4_K_M.gguf
ctx-size = 262144
cache-type-k = q8_0
cache-type-v = q8_0
cache-type-k-draft = q8_0
cache-type-v-draft = q8_0
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 0.6
top-k = 20

[Ornith-1.0-9B-256K-Q80-Q4-MTP]
model = /models/protoLabsAI/Ornith-1.0-9B-MTP-GGUF/ornith-9b-mtp-kl-Q8_0.gguf
ctx-size = 262144
cache-type-k-draft = q4_0
cache-type-v-draft = q4_0
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 0.6
top-k = 20

[Ornith-1.0-9B-256K-Q80-Q8-MTP]; 17.680Gi/24Gi
model = /models/protoLabsAI/Ornith-1.0-9B-MTP-GGUF/ornith-9b-mtp-kl-Q8_0.gguf
ctx-size = 262144
cache-type-k = q8_0
cache-type-v = q8_0
cache-type-k-draft = q8_0
cache-type-v-draft = q8_0
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 0.6
top-k = 20

[Ornith-1.0-9B-512K-Q80-Q4-MTP]; 20.964Gi/24Gi
model = /models/protoLabsAI/Ornith-1.0-9B-MTP-GGUF/ornith-9b-mtp-kl-Q8_0.gguf
ctx-size = 524288
rope-scaling = yarn
rope-scale = 2
yarn-orig-ctx = 262144
cache-type-k = q4_0
cache-type-v = q4_0
cache-type-k-draft = q4_0
cache-type-v-draft = q4_0
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 0.6
top-k = 20

